=== evgenymalishevskiy/JD2018-11-13/src/by/it/lobkova/jd02_09/person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.lobkova.it.by"
        xmlns:mtp="http://beans.jd02_09.lobkova.it.by"
        elementFormDefault="qualified">
    <element name="persons">
        <complexType>
            <sequence>
                <element name="person"
                         type="mtp:person"
                         minOccurs="1"
                         maxOccurs="unbounded"
                />
            </sequence>
        </complexType>
    </element>

    <complexType name="person">
        <sequence>
            <element name="email" type="string"/>
            <element name="nickname" type="string"/>
            <element name="password" type="string"/>
            <element name="goals" type="mtp:goals"/>
        </sequence>
    </complexType>

    <complexType name="goals">
        <sequence>
            <element
                    name="goal"
                    type="mtp:goal"
                    minOccurs="0"
                    maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="goal">
        <sequence>
            <element name="name_goal" type="string"/>
            <element name="description_goal" type="string"/>
            <element name="startTime" type="string"/>
            <element name="endTime" type="string"/>
            <element name="tasks" type="mtp:tasks"/>
        </sequence>
    </complexType>

    <complexType name="tasks">
        <sequence>
            <element
                    name="task"
                    type="mtp:task"
                    minOccurs="0"
                    maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="task">
        <sequence>
            <element name="name_task" type="string"/>
            <element name="description_task" type="string"/>
            <element name="date" type="string"/>
            <element name="repeat" type="string"/>
        </sequence>
    </complexType>

</schema>

=== evgenymalishevskiy/JD2018-11-13/src/by/it/lobkova/jd02_09/person+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://beans.jd02_09.lobkova.it.by"
         xsi:schemaLocation="http://beans.jd02_09.lobkova.it.by  person.xsd"
>
    <person>
    <email>dashabertosh@gmail.com</email>
    <nickname>Dasha_Bertosh</nickname>
    <password>bertosh1980</password>
    <goals>
        <goal>
            <name_goal>Похудеть на 8 кг</name_goal>
            <description_goal>В течении заданного времени похудеть на 8 кг и накачать пресс</description_goal>
            <startTime>01.01.2019</startTime>
            <endTime>01.03.2019</endTime>
            <tasks>
                <task>
                    <name_task>Уренняя пробежка</name_task>
                    <description_task>Выполнить утреннюю пробежку 3 км вокруг стадиона</description_task>
                    <date>02.01.2019</date>
                    <repeat>Каждый вторник</repeat>
                </task>
                <task>
                    <name_task>Исключить вредные продукты</name_task>
                    <description_task>Исключить из рациона жаренное, мучное, сладкое</description_task>
                    <date>01.01.2019</date>
                    <repeat>Каждый день</repeat>
                </task>
            </tasks>
        </goal>
    </goals>
</person>
</persons>
