=== evgenymalishevskiy/JD2018-11-13/src/by/it/seroglazov/project/java/dao/xml/recipes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://xml.jd03_03.seroglazov.it.by/recipes"
        xmlns:mtp="http://xml.jd03_03.seroglazov.it.by/recipes"
        elementFormDefault="qualified">

    <element name="recipes">
        <complexType>
            <sequence>
                <element name="recipe" type="mtp:Recipe" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Recipe">
        <sequence>
            <element name="name" type="string"/>
            <element name="type" type="string"/>
            <element name="description" type="string"/>
            <element name="ingredient" type="mtp:Ingredient" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Ingredient">
        <sequence>
            <element name="name" type="string"/>
            <element name="amount" type="string"/>
            <element name="unit" type="string"/>
        </sequence>
    </complexType>

</schema>

=== evgenymalishevskiy/JD2018-11-13/src/by/it/seroglazov/jd03_03/xml/recipes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://xml.jd03_03.seroglazov.it.by/recipes"
         xsi:schemaLocation="http://xml.jd03_03.seroglazov.it.by/recipes recipes.xsd">
    <recipe>
        <name>white lady</name>
        <type>all day cocktail</type>
        <description>Add all ingredients into cocktail shaker filled with ice. Shake well and strain into large cocktail glass.</description>
        <ingredient>
            <name>gin</name>
            <amount>4</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>triple sec</name>
            <amount>3</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>fresh lemon juice</name>
            <amount>2</amount>
            <unit>cl</unit>
        </ingredient>
    </recipe>
    <recipe>
        <name>old fashioned</name>
        <type>before dinner cocktail</type>
        <description>Place sugar cube in old-fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolve. Fill the glass with ice cubes and add whiskey. Garnish with orange slice and a cocktail cherry.</description>
        <ingredient>
            <name>bourbon whiskey</name>
            <amount>4.5</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>angostura aromatic bitters</name>
            <amount>2</amount>
            <unit>dash</unit>
        </ingredient>
        <ingredient>
            <name>plain water</name>
            <amount>few</amount>
            <unit>dash</unit>
        </ingredient>
    </recipe>
    <recipe>
        <name>margarita</name>
        <type>all day cocktail</type>
        <description>Pour all ingredients into shaker with ice. Shake well and strain into cocktail glass rimmed with salt (note:Fruit Margarita â€“ blend selected fruit with the above recipe).</description>
        <ingredient>
            <name>tequila</name>
            <amount>3.5</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>cointreau</name>
            <amount>2</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>fresh lime juice</name>
            <amount>1.5</amount>
            <unit>cl</unit>
        </ingredient>
    </recipe>
    <recipe>
        <name>cuba libre</name>
        <type>longdrink</type>
        <description>Build all ingredients in a highball glass filled with ice. Garnish with lime wedge.</description>
        <ingredient>
            <name>white rum</name>
            <amount>5</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>cola</name>
            <amount>12</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>fresh lime juice</name>
            <amount>1</amount>
            <unit>cl</unit>
        </ingredient>
    </recipe>
    <recipe>
        <name>mojito</name>
        <type>longdrink</type>
        <description>Muddle mint springs with sugar and lime juice. Add splash of soda water and fill glass with cracked ice. Pour rum and top with soda water. Garnish with spring of mint leaves and lemon slice. Serve with straw.</description>
        <ingredient>
            <name>white rum</name>
            <amount>4</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>fresh lime juice</name>
            <amount>3</amount>
            <unit>cl</unit>
        </ingredient>
        <ingredient>
            <name>mint</name>
            <amount>6</amount>
            <unit>sprig</unit>
        </ingredient>
        <ingredient>
            <name>soda water</name>
            <amount>top</amount>
            <unit>none</unit>
        </ingredient>
    </recipe>
</recipes>
